from enum import Enum

class Provider(str, Enum):
    SCAPY = "scapy"
    PYCRATE = "pycrate"

# Global registry for dissector classes
DISSECTOR_REGISTRY = []

def register_dissector(cls):
    # Store the CLASS, not an instance
    DISSECTOR_REGISTRY.append(cls)
    return cls

def get_dissectors():
    return DISSECTOR_REGISTRY

def load_handlers():
    """Import handlers to trigger registration decorator."""
    try:
        import handlers.scapy_handler
        import handlers.generic_handler
    except ImportError as e:
        print(f"Warning: Failed to load handlers: {e}")

# AUTHORITATIVE METADATA
# Key must match the Template filename (without .py)
PROTOCOL_METADATA = {
    # --- TELCO (Pycrate) ---
    "M3UA": { "provider": Provider.PYCRATE, "class": "M3UA.M3UA_PDU_Descriptions.M3UA_PDU", "payload_field": "data" },
    "SCCP": { "provider": Provider.PYCRATE, "class": "SCCP.SCCP_PDU_Descriptions.SCCP_PDU", "payload_field": "data" },
    "TCAP": { "provider": Provider.PYCRATE, "class": "TCAP_MAPv2v3.TCAP_MAP_Messages.TCAP_MAP_Message", "payload_field": "components" },
    "TCAP_MAP": { "provider": Provider.PYCRATE },
    "Diameter": { "provider": Provider.PYCRATE },
    "GTP": { "provider": Provider.PYCRATE },
    "NGAP": { "provider": Provider.PYCRATE, "class": "NGAP.NGAP_PDU_Descriptions.NGAP_PDU", "method": "aper", "payload_field": "value" },
    "S1AP": { "provider": Provider.PYCRATE, "class": "S1AP.S1AP_PDU_Descriptions.S1AP_PDU", "method": "aper", "payload_field": "value" },
    
    # --- STANDARD (Scapy) ---
    "OpenVPN": { "provider": Provider.SCAPY },
    "Telnet": { "provider": Provider.SCAPY, "payload_field": "data" },
    "TNS": { "provider": Provider.SCAPY },
    "S7Comm": { "provider": Provider.SCAPY },
    "IEC104": { "provider": Provider.SCAPY },
    "MMS_IEC61850": { "provider": Provider.SCAPY },  # IEC 61850 Manufacturing Message Specification
    "MMS_WAP": { "provider": Provider.SCAPY },  # WAP Multimedia Messaging Service
    "H265": { "provider": Provider.SCAPY },
    "BFD": { "provider": Provider.SCAPY },
    "PTP": { "provider": Provider.SCAPY },
    "MySQL": { "provider": Provider.SCAPY },
    "HTTP2": { "provider": Provider.SCAPY },
    "RTSP": { "provider": Provider.SCAPY },
    "EAPOL": { "provider": Provider.SCAPY },
    "HSRP": { "provider": Provider.SCAPY },
    "NFS": { "provider": Provider.SCAPY },
    "IMAP": { "provider": Provider.SCAPY },
    "FTP": { "provider": Provider.SCAPY },
    "SMTP": { "provider": Provider.SCAPY },
    "POP3": { "provider": Provider.SCAPY },
    "SSH": { "provider": Provider.SCAPY },
    "LDAP": { "provider": Provider.SCAPY },
    "Telnet": { "provider": Provider.SCAPY },
    "MGCP": { "provider": Provider.SCAPY },
    "DNS": { "provider": Provider.SCAPY },
    "IPv6": { "provider": Provider.SCAPY },
    "CDP": { "provider": Provider.SCAPY },
    "SMB": { "provider": Provider.SCAPY },
    "CAMEL": { "provider": Provider.PYCRATE },
    "Ethernet": { "provider": Provider.SCAPY, "payload_field": "load" },
    "IP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "IPv6": { "provider": Provider.SCAPY, "payload_field": "load" },
    "UDP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "TCP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "SCTP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "SCTPChunkData": { "provider": Provider.SCAPY, "payload_field": "data" },
    "SCTPChunkSACK": { "provider": Provider.SCAPY },
    "SCTPChunkInit": { "provider": Provider.SCAPY },
    "SCTPChunkInitAck": { "provider": Provider.SCAPY },
    "SCTPChunkCookieEcho": { "provider": Provider.SCAPY },
    "SCTPChunkCookieAck": { "provider": Provider.SCAPY },
    "SCTPChunkHeartbeat": { "provider": Provider.SCAPY },
    "SCTPChunkError": { "provider": Provider.SCAPY },
    "SCTPChunkAbort": { "provider": Provider.SCAPY },
    "SCTPChunkShutdown": { "provider": Provider.SCAPY },
    "SCTPChunkShutdownAck": { "provider": Provider.SCAPY },
    "SCTPChunkShutdownComplete": { "provider": Provider.SCAPY },
    "ICMP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "ICMPv6": { "provider": Provider.SCAPY, "payload_field": "load" },
    "ICMPv6NDOptSrcLLAddr": { "provider": Provider.SCAPY, "payload_field": "load" },
    "ICMPv6NDOptDstLLAddr": { "provider": Provider.SCAPY, "payload_field": "load" },
    "ICMPv6ND_NS": { "provider": Provider.SCAPY, "payload_field": "load" },
    "ICMPv6ND_NA": { "provider": Provider.SCAPY, "payload_field": "load" },
    "DNS": { "provider": Provider.SCAPY },
    "ARP": { "provider": Provider.SCAPY },
    "Raw": { "provider": Provider.SCAPY, "payload_field": "load" },
    "Padding": { "provider": Provider.SCAPY, "payload_field": "load" },
    "CDP": { "provider": Provider.SCAPY }, # Added CDP
    "BGP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "OSPF": { "provider": Provider.SCAPY, "payload_field": "load" },
    "MPLS": { "provider": Provider.SCAPY, "payload_field": "load" },
    "TFTP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "TFTP_RRQ": { "provider": Provider.SCAPY },
    "TFTP_WRQ": { "provider": Provider.SCAPY },
    "TFTP_DATA": { "provider": Provider.SCAPY, "payload_field": "load" },
    "TFTP_ACK": { "provider": Provider.SCAPY },
    "TFTP_ERROR": { "provider": Provider.SCAPY },
    "TFTP_OACK": { "provider": Provider.SCAPY },
    "STP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "LLDP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "AH": { "provider": Provider.SCAPY, "payload_field": "load" },
    "ESP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "MQTT": { "provider": Provider.SCAPY, "payload_field": "load" },
    "ISIS": { "provider": Provider.SCAPY, "payload_field": "load" },
    "VRRP": { "provider": Provider.SCAPY },
    "CoAP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "MobileIP": { "provider": Provider.SCAPY },
    "EIGRP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "SIP": { "provider": Provider.SCAPY },
    "RTP": { "provider": Provider.SCAPY },
    "SMB2_Header": { "provider": Provider.SCAPY },
    "DNP3": { "provider": Provider.SCAPY },
    "ZigbeeNWK": { "provider": Provider.SCAPY },
    "Kerberos": { "provider": Provider.SCAPY },
    "Netlink": { "provider": Provider.SCAPY },
    "DCERPC": { "provider": Provider.SCAPY },
    "TDS": { "provider": Provider.SCAPY },
    "GRE": { "provider": Provider.SCAPY },
    "VXLAN": { "provider": Provider.SCAPY },
    "L2TP": { "provider": Provider.SCAPY },
    "Modbus": { "provider": Provider.SCAPY },
    "DCCP": { "provider": Provider.SCAPY },
    "LoRaWAN": { "provider": Provider.SCAPY },
    "ISUP": { "provider": Provider.PYCRATE },
    "MTP3": { "provider": Provider.PYCRATE },
    "M2UA": { "provider": Provider.PYCRATE },
    "GTPv2C": { "provider": Provider.PYCRATE },
    "NAS5G": { "provider": Provider.PYCRATE },
    "NASLTE": { "provider": Provider.PYCRATE },
    "SMS": { "provider": Provider.PYCRATE },
    "RADIUS": { "provider": Provider.SCAPY },
    "UDS": { "provider": Provider.SCAPY },
    "DoIP": { "provider": Provider.SCAPY },
    "SOMEIP": { "provider": Provider.SCAPY },
    "NTLM": { "provider": Provider.SCAPY },
    "CAP": { "provider": Provider.PYCRATE }, # Placeholder
    "PFCP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "SixLoWPAN": { "provider": Provider.SCAPY, "payload_field": "load" },
    "Dot15d4": { "provider": Provider.SCAPY, "payload_field": "load" },
    "BOOTP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "DHCP": { "provider": Provider.SCAPY },
    "HTTP": { "provider": Provider.SCAPY },
    "RIP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "RIPEntry": { "provider": Provider.SCAPY, "payload_field": "load" },
    "PPPoE": { "provider": Provider.SCAPY, "payload_field": "load" },
    "PPP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "PPPoED": { "provider": Provider.SCAPY, "payload_field": "tags" },
    "PPPoED_Tags": { "provider": Provider.SCAPY, "payload_field": "load" },
    "PPP_LCP_Configure": { "provider": Provider.SCAPY, "payload_field": "load" },
    "PPP_LCP_Terminate": { "provider": Provider.SCAPY, "payload_field": "load" },
    "PPP_PAP_Request": { "provider": Provider.SCAPY, "payload_field": "load" },
    "TLS": { "provider": Provider.SCAPY, "payload_field": "load" },
    "CookedLinux": { "provider": Provider.SCAPY, "payload_field": "load" },
    
    # --- OTHERS ---
    "HDLC": { "provider": Provider.SCAPY, "payload_field": "load" },
    "LLC": { "provider": Provider.SCAPY, "payload_field": "load" },
    "SNAP": { "provider": Provider.SCAPY, "payload_field": "load" },
    "Dot3": { "provider": Provider.SCAPY, "payload_field": "load" },
    "SMB_Header": { "provider": Provider.SCAPY },
}

# Mapping from common variants to authoritative keys
PROTOCOL_MAP = {
    "openvpn": "OpenVPN",
    "telnet": "Telnet",
    "tns": "TNS",
    "s7comm": "S7Comm",
    "iec104": "IEC104", "104apci": "IEC104",
    "mms": "MMS_IEC61850",  # IEC 61850 MMS (industrial)
    "wsp": "MMS_WAP", "wap_mms": "MMS_WAP",  # WAP Multimedia Messaging Service
    "h265": "H265", "hevc": "H265",
    "bfd": "BFD",
    "ptp": "PTP", "ptpv2": "PTP",
    "mysql": "MySQL",
    "http2": "HTTP2",
    "eapol": "EAPOL",
    "dns": "DNS",
    "ipv6": "IPv6",
    "cdp": "CDP",
    "smb": "SMB_Header", "smb2": "SMB2_Header", "netbios_ssn": "SMB_Header", # Broad mapping for SMB stack
    "eth": "Ethernet", "ether": "Ethernet", "ethernet": "Ethernet",
    "ip": "IP", "ipv4": "IP",
    "ipv6": "IPv6",
    "udp": "UDP",
    "tcp": "TCP",
    "sctp": "SCTP",
    "m3ua": "M3UA",
    "sccp": "SCCP",
    "tcap": "TCAP",
    "gsm_map": "TCAP_MAP",
    "gtp": "GTP", "gtpv1": "GTP", "gtpv2": "GTP",
    "diameter": "Diameter",
    "icmp": "ICMP",
    "icmpv6": "ICMPv6",
    "icmpv6ndoptsrclladdr": "ICMPv6NDOptSrcLLAddr",
    "icmpv6ndoptdstlladdr": "ICMPv6NDOptDstLLAddr",
    "icmpv6nd_ns": "ICMPv6ND_NS",
    "icmpv6nd_na": "ICMPv6ND_NA",
    "dns": "DNS",
    "arp": "ARP",
    "igmp": "IGMP",
    "sixlowpan": "SixLoWPAN",
    "6lowpan": "SixLoWPAN", # Added variant
    "wpan": "Dot15d4",
    "dot15d4": "Dot15d4",
    "wpan-tap": "WTAP",
    "bootp": "BOOTP",
    "dhcp": "DHCP",
    "rip": "RIP",
    "ripentry": "RIPEntry",
    "http": "HTTP",
    "llc": "LLC",
    "snap": "SNAP",
    "dot3": "Dot3",
    "cdp": "CDP", # Added CDP
    "bgp": "BGP",
    "ospf": "OSPF",
    "mpls": "MPLS",
    "tftp": "TFTP",
    "tftp.rrq": "TFTP_RRQ", "tftp_rrq": "TFTP_RRQ",
    "tftp.wrq": "TFTP_WRQ", "tftp_wrq": "TFTP_WRQ",
    "tftp.data": "TFTP_DATA", "tftp_data": "TFTP_DATA",
    "tftp.ack": "TFTP_ACK", "tftp_ack": "TFTP_ACK",
    "tftp.error": "TFTP_ERROR", "tftp_error": "TFTP_ERROR",
    "tftp.oack": "TFTP_OACK", "tftp_oack": "TFTP_OACK",
    "stp": "STP",
    "lldp": "LLDP",
    "ah": "AH",
    "esp": "ESP",
    "mqtt": "MQTT",
    "isis": "ISIS",
    "vrrp": "VRRP",
    "coap": "CoAP",
    "mobileip": "MobileIP", "mip": "MobileIP",
    "eigrp": "EIGRP",
    "sip": "SIP",
    "rtp": "RTP",
    "smb2": "SMB2",
    "dnp3": "DNP3",
    "zbee_nwk": "ZigbeeNWK", "zigbee": "ZigbeeNWK",
    "krb5": "Kerberos", "kerberos": "Kerberos",
    "netlink": "Netlink",
    "dcerpc": "DCERPC",
    "tds": "TDS",
    "gre": "GRE",
    "vxlan": "VXLAN",
    "l2tp": "L2TP",
    "mbtcp": "Modbus", "modbus": "Modbus",
    "dccp": "DCCP",
    "lorawan": "LoRaWAN",
    "isup": "ISUP",
    "mtp3": "MTP3",
    "m2ua": "M2UA",
    "uds": "UDS",
    "doip": "DoIP",
    "someip": "SOMEIP",
    "ntlm": "NTLM", "ntlmssp": "NTLM",
    "camel": "CAMEL",
    "eth": "Ethernet", "ether": "Ethernet", "ethernet": "Ethernet",
    "pfcp": "PFCP",
    "ipx": "IPX", # Added IPX
    "pppoe": "PPPoE",
    "ppp": "PPP",
    "pppoed": "PPPoED",
    "pppoed_tags": "PPPoED_Tags",
    "ppp_lcp_configure": "PPP_LCP_Configure",
    "ppp_lcp_terminate": "PPP_LCP_Terminate",
    "ppp_pap_request": "PPP_PAP_Request",
    "tls": "TLS",
    "sll": "CookedLinux",
    "ngap": "NGAP",
    "s1ap": "S1AP",
    "gtpv2c": "GTPv2C", "gtpv2-c": "GTPv2C",
    "nas5g": "NAS5G", "nas-5g": "NAS5G", "5g-nas": "NAS5G",
    "sms": "SMS", "gsm_sms": "SMS",
    "radius": "RADIUS",
    "ftp": "FTP",
    "smtp": "SMTP",
    "pop": "POP3", "pop3": "POP3",
    "imap": "IMAP",
    "ssh": "SSH",
    "ldap": "LDAP",
    "telnet": "Telnet",
    "rtsp": "RTSP",
    "naslte": "NASLTE", "nas-lte": "NASLTE", "lte-nas": "NASLTE",
}

__all__ = ["PROTOCOL_METADATA", "Provider", "PROTOCOL_MAP", "get_dissectors", "load_handlers"]